"""add session_length_minutes to availability_slot

Revision ID: 5486878c6602
Revises: 56351783ed2c
Create Date: 2026-07-12 14:02:39.432234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5486878c6602'
down_revision = '56351783ed2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability_slot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_length_minutes', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability_slot', schema=None) as batch_op:
        batch_op.drop_column('session_length_minutes')

    # ### end Alembic commands ###
