"""Initial migration

Revision ID: e291f02e3abe
Revises: b7d859bf4021
Create Date: 2026-07-01 00:43:30.621133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e291f02e3abe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=32), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('session_token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_email_hash'), ['email_hash'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_audit_log_user_action', ['user_id', 'action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('therapist',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('license_number_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('license_verified_at', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('specialties', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('session_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('therapist_notes', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapist.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_scheduled_for'), ['scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_therapist_id'), ['therapist_id'], unique=False)
        batch_op.create_index('ix_appointment_therapist_scheduled', ['therapist_id', 'scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_appointment_user_scheduled', ['user_id', 'scheduled_for'], unique=False)

    op.create_table('availability_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('specific_date', sa.Date(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapist.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availability_slot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availability_slot_therapist_id'), ['therapist_id'], unique=False)

    op.create_table('chat_thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('therapist_id', sa.Integer(), nullable=True),
    sa.Column('peer_listener_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['peer_listener_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapist.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_thread', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_thread_therapist_id'), ['therapist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_thread_user_id'), ['user_id'], unique=False)

    op.create_table('client_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('body_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=True),
    sa.Column('diagnosis_tags', sa.String(length=500), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapist.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_note_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_note_therapist_id'), ['therapist_id'], unique=False)

    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('flagged_reason', sa.String(length=200), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('original_body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_thread.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index('ix_chat_message_thread_sent', ['thread_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_message_thread_sent')
        batch_op.drop_index(batch_op.f('ix_chat_message_thread_id'))
        batch_op.drop_index(batch_op.f('ix_chat_message_sender_id'))

    op.drop_table('chat_message')
    with op.batch_alter_table('client_note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_note_therapist_id'))
        batch_op.drop_index(batch_op.f('ix_client_note_client_id'))

    op.drop_table('client_note')
    with op.batch_alter_table('chat_thread', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_thread_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_thread_therapist_id'))

    op.drop_table('chat_thread')
    with op.batch_alter_table('availability_slot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availability_slot_therapist_id'))

    op.drop_table('availability_slot')
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_index('ix_appointment_user_scheduled')
        batch_op.drop_index(batch_op.f('ix_appointment_user_id'))
        batch_op.drop_index('ix_appointment_therapist_scheduled')
        batch_op.drop_index(batch_op.f('ix_appointment_therapist_id'))
        batch_op.drop_index(batch_op.f('ix_appointment_scheduled_for'))

    op.drop_table('appointment')
    op.drop_table('therapist')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index('ix_audit_log_user_action')
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email_hash'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
